using Dapper;
using Microsoft.Data.Sqlite;
using HomepalMockAPI.DatabaseConfiguration;
using System.Threading.Tasks;
using HomepalMockAPI.Models;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System;
using System.Diagnostics;

namespace HomepalMockAPI.DAL
{
    public class BuildingsRepository : IBuildingsRepository
    {
        private readonly DatabaseConfig databaseConfig;

        public BuildingsRepository(DatabaseConfig databaseConfig)
        {
            this.databaseConfig = databaseConfig;
        }

        private Boolean _IsTable(IEnumerable<dynamic> tables, string sort)
        {
            foreach (var item in tables)
            {
                if (item.name.Equals(sort))
                {
                    return true;
                }
            }
            return false;
        }

        private Boolean _IsDesc(string sort)
        {
            return sort.StartsWith("-");
        }

        private string _FormatSortParam(string sort)
        {
            return sort.Substring(1);
        }

        /* Returns all fields on all Buildings */
        public async Task<IEnumerable<Building>> Get(int limit, int offset, string sort)
        {
            using var connection = new SqliteConnection(databaseConfig.Name);
            var parameters = new DynamicParameters();
            parameters.Add("@limit", limit, DbType.Int32, ParameterDirection.Input);
            parameters.Add("@offset", offset, DbType.Int32, ParameterDirection.Input);
            var isDesc = _IsDesc(sort);

            if (isDesc)
            {
                sort = _FormatSortParam(sort);
            }

            var tables = await connection.QueryAsync("PRAGMA table_info(Buildings);");

            var isTable = _IsTable(tables, sort);

            if (_IsTable(tables, sort))
            {
                if (limit != 0 && offset != 0 && isTable)
                {
                    if (isDesc)
                    {
                        return await connection.QueryAsync<Building>("SELECT * FROM Buildings ORDER BY " + sort + " DESC LIMIT @limit OFFSET @offset", parameters);
                    }
                    return await connection.QueryAsync<Building>("SELECT * FROM Buildings ORDER BY " + sort + " LIMIT @limit OFFSET @offset", parameters);
                }
                else if (limit != 0 && offset == 0 && isTable)
                {
                    if (isDesc)
                    {
                        return await connection.QueryAsync<Building>("SELECT * FROM Buildings ORDER BY " + sort + " DESC LIMIT @limit", parameters);
                    }
                    return await connection.QueryAsync<Building>("SELECT * FROM Buildings ORDER BY " + sort + " LIMIT @limit", parameters);
                }
                else if (offset != 0 && limit == 0)
                {
                    if (isDesc)
                    {
                        return await connection.QueryAsync<Building>("SELECT * FROM Buildings ORDER BY " + sort + " DESC LIMIT -1 OFFSET @offset", parameters);
                    }
                    return await connection.QueryAsync<Building>("SELECT * FROM Buildings ORDER BY " + sort + " LIMIT -1 OFFSET @offset", parameters);
                }
                else
                {
                    if (isDesc)
                    {
                        return await connection.QueryAsync<Building>("SELECT * FROM Buildings ORDER BY " + sort + " DESC LIMIT 10");
                    }
                    return await connection.QueryAsync<Building>("SELECT * FROM Buildings ORDER BY " + sort + " LIMIT 10");
                }
            }
            else
            {
                return await connection.QueryAsync<Building>("SELECT * FROM Buildings LIMIT 10");
            }

        }

        /* Returns all fields on a Building based on id */
        public async Task<Building> GetSingle(int id)
        {
            using var connection = new SqliteConnection(databaseConfig.Name);
            var parameters = new DynamicParameters();
            parameters.Add("@id", id, DbType.Int32, ParameterDirection.Input);

            return await connection.QuerySingleAsync<Building>("SELECT * FROM Buildings WHERE [id] = @id;", parameters);
        }

        /* Creates a new Building. ID is generated by DB. 
           @Returns number of row affected. */
        public async Task<int> Create(Building building)
        {
            using var connection = new SqliteConnection(databaseConfig.Name);

            return await connection.ExecuteAsync("INSERT INTO Buildings (class_descriptor, street_name, street_number, postal_code, real_estate_id)" +
                "VALUES (@class_descriptor, @street_name, @street_number, @postal_code, @real_estate_id);", building);
        }

        /* Updates fields of a Building based on ID. 
           @Returns number of row affected. */
        public async Task<int> Update(Building building)
        {
            using var connection = new SqliteConnection(databaseConfig.Name);
            return await connection.ExecuteAsync("UPDATE Buildings SET [class_descriptor] = @class_descriptor, [street_name] = @street_name, [street_number] = @street_number, [postal_code] = @postal_code WHERE id = @id", building);
        }

        /* Deletes a Building based on id
           @Returns number of row affected. */
        public async Task<int> Delete(int id)
        {
            using var connection = new SqliteConnection(databaseConfig.Name);
            var parameters = new DynamicParameters();
            parameters.Add("@id", id, DbType.Int32, ParameterDirection.Input);

            return await connection.ExecuteAsync("DELETE FROM Buildings WHERE [id] = @id;", parameters);
        }
    }
}