using Dapper;
using Microsoft.Data.Sqlite;
using HomepalMockAPI.DatabaseConfiguration;
using System.Threading.Tasks;
using HomepalMockAPI.Models;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System;
using System.Diagnostics;

namespace HomepalMockAPI.DAL
{
    public class LeasablesRepository : ILeasablesRepository
    {
        private readonly DatabaseConfig databaseConfig;

        public LeasablesRepository(DatabaseConfig databaseConfig)
        {
            this.databaseConfig = databaseConfig;
        }

        private Boolean _IsTable(IEnumerable<dynamic> tables, string sort)
        {
            foreach (var item in tables)
            {
                if (item.name.Equals(sort))
                {
                    return true;
                }
            }
            return false;
        }

        private Boolean _IsDesc(string sort)
        {
            return sort.StartsWith("-");
        }

        private string _FormatSortParam(string sort)
        {
            return sort.Substring(1);
        }

        /* Returns all fields on all Leasables */
        public async Task<IEnumerable<Leasable>> Get(int limit, int offset, string sort)
        {
            using var connection = new SqliteConnection(databaseConfig.Name);
            var parameters = new DynamicParameters();
            parameters.Add("@limit", limit, DbType.Int32, ParameterDirection.Input);
            parameters.Add("@offset", offset, DbType.Int32, ParameterDirection.Input);
            string sortString = " ";

            if (!String.IsNullOrEmpty(sort))
            {
                var tables = await connection.QueryAsync("PRAGMA table_info(Leasables);");
                // OM vi inte har minus framför, och den är en tabell. Sortera som vanligt!
                if (!_IsDesc(sort) && _IsTable(tables, sort))
                {
                    sortString = " ORDER BY " + sort + " ";
                }
                else if (_IsDesc(sort))
                {
                    sort = _FormatSortParam(sort);
                    if (_IsTable(tables, sort))
                    {
                        sortString = " ORDER BY " + sort + " DESC ";
                    }

                }
            }

            if (limit != 0 && offset != 0)
            {
                return await connection.QueryAsync<Leasable>("SELECT * FROM Leasables" + sortString + "LIMIT @limit OFFSET @offset", parameters);
            }
            else if (limit != 0 && offset == 0)
            {
                return await connection.QueryAsync<Leasable>("SELECT * FROM Leasables" + sortString + "LIMIT @limit", parameters);
            }
            else if (offset != 0 && limit == 0)
            {
                return await connection.QueryAsync<Leasable>("SELECT * FROM Leasables" + sortString + "LIMIT -1 OFFSET @offset", parameters);
            }
            else
            {
                return await connection.QueryAsync<Leasable>("SELECT * FROM Leasables" + sortString + "LIMIT 10");
            }

        }

        /* Returns all fields on a Leasable based on id */
        public async Task<Leasable> GetSingle(int id)
        {
            using var connection = new SqliteConnection(databaseConfig.Name);
            var parameters = new DynamicParameters();
            parameters.Add("@id", id, DbType.Int32, ParameterDirection.Input);

            try
            {
                return await connection.QuerySingleAsync<Leasable>("SELECT * FROM Leasables WHERE [id] = @id;", parameters);
            }

            catch (Exception)
            {
                return null;
            }
        }

        /* Creates a new Leasable. ID is generated by DB. 
           @Returns number of row affected. */
        public async Task<int> Create(Leasable leasable)
        {
            using var connection = new SqliteConnection(databaseConfig.Name);

            return await connection.ExecuteAsync("INSERT INTO Leasables (class_descriptor, price, description, size, customer_id, owner_id, building_id)" +
                "VALUES (@class_descriptor, @price, @description, @size, @CustomerId, @owner_id, @building_id);", leasable);
        }

        /* Updates fields of a Leasable based on ID. 
           @Returns number of row affected. */
        public async Task<int> Update(Leasable leasable)
        {
            using var connection = new SqliteConnection(databaseConfig.Name);
            return await connection.ExecuteAsync("UPDATE Leasables SET [class_descriptor] = @class_descriptor, [price] = @price, [description] = @description, [size] = @size, [CustomerId] = @CustomerId, [owner_id] = @owner_id WHERE id= @id", leasable);
        }

        /* Deletes a Leasable based on id
           @Returns number of row affected. */
        public async Task<int> Delete(int id)
        {
            using var connection = new SqliteConnection(databaseConfig.Name);
            var parameters = new DynamicParameters();
            parameters.Add("@id", id, DbType.Int32, ParameterDirection.Input);

            return await connection.ExecuteAsync("DELETE FROM Leasables WHERE [id] = @id;", parameters);
        }
    }
}