using Dapper;
using Microsoft.Data.Sqlite;
using HomepalMockAPI.DatabaseConfiguration;
using System.Threading.Tasks;
using HomepalMockAPI.Models;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System;
using System.Diagnostics;

namespace HomepalMockAPI.DAL
{
    public class OwnersRepository : IOwnersRepository
    {
        private readonly DatabaseConfig databaseConfig;

        public OwnersRepository(DatabaseConfig databaseConfig)
        {
            this.databaseConfig = databaseConfig;
        }

        private Boolean _IsTable(IEnumerable<dynamic> tables, string sort)
        {
            foreach (var item in tables)
            {
                if (item.name.Equals(sort))
                {
                    return true;
                }
            }
            return false;
        }

        private Boolean _IsDesc(string sort)
        {
            return sort.StartsWith("-");
        }

        private string _FormatSortParam(string sort)
        {
            return sort.Substring(1);
        }

        /* Returns all fields on all Owners */
        public async Task<IEnumerable<Owner>> Get(int limit, int offset, string sort)
        {
            using var connection = new SqliteConnection(databaseConfig.Name);
            var parameters = new DynamicParameters();

            if (limit != 0 && offset != 0)
            {
                parameters.Add("@limit", limit, DbType.Int32, ParameterDirection.Input);
                parameters.Add("@offset", offset, DbType.Int32, ParameterDirection.Input);
                return await connection.QueryAsync<Owner>("SELECT * FROM Owners LIMIT @limit OFFSET @offset", parameters);
            }
            else if (limit != 0 && offset == 0)
            {
                parameters.Add("@limit", limit, DbType.Int32, ParameterDirection.Input);
                return await connection.QueryAsync<Owner>("SELECT * FROM Owners LIMIT @limit", parameters);
            }
            else if (offset != 0 && limit == 0)
            {
                parameters.Add("@offset", offset, DbType.Int32, ParameterDirection.Input);
                return await connection.QueryAsync<Owner>("SELECT * FROM Owners LIMIT -1 OFFSET @offset", parameters);
            }
            else
            {
                return await connection.QueryAsync<Owner>("SELECT * FROM Owners LIMIT 10");
            }
        }

        /* Returns all fields on a Owner based on id */
        public async Task<Owner> GetSingle(int id)
        {
            using var connection = new SqliteConnection(databaseConfig.Name);
            var parameters = new DynamicParameters();
            parameters.Add("@id", id, DbType.Int32, ParameterDirection.Input);

            return await connection.QuerySingleAsync<Owner>("SELECT * FROM Owners WHERE [id] = @id;", parameters);
        }

        /* Creates a new Owner. ID is generated by DB. 
           @Returns number of row affected. */
        public async Task<int> Create(Owner owner)
        {
            using var connection = new SqliteConnection(databaseConfig.Name);

            return await connection.ExecuteAsync("INSERT INTO Owners (id)" +
                "VALUES (@id);", owner);
        }

        /* Deletes a Owner based on id
           @Returns number of row affected. */
        public async Task<int> Delete(int id)
        {
            using var connection = new SqliteConnection(databaseConfig.Name);
            var parameters = new DynamicParameters();
            parameters.Add("@id", id, DbType.Int32, ParameterDirection.Input);

            return await connection.ExecuteAsync("DELETE FROM Owners WHERE [id] = @id;", parameters);
        }
    }
}